project:
  type: book
  output-dir: docs
  
book:
  title: "Data Visualization notes"
  author: "Andrew Irwin"
  date: "2022-09-06"
  chapters:
    - index.qmd
    - lessons/101-introduction.Rmd
    - lessons/102-intro-to-r.Rmd
    - lessons/103-setup.Rmd
    - lessons/104-look-at-data.Rmd
    - lessons/105-first-plot.Rmd
    - lessons/106-version-control.Rmd
    - lessons/302-staying-organized.Rmd
    - lessons/107-grammar-graphics.Rmd
    - lessons/108-ggplot.Rmd
    # - lessons/109-scales.Rmd
    - lessons/110-summarizing-data.Rmd
    - lessons/115-facets.Rmd
    - lessons/111-reading-data.Rmd
    - lessons/112-reshaping-data.Rmd
    - lessons/113-data-tables.Rmd
    - lessons/114-asking-questions.Rmd
    - lessons/118-working-with-models.Rmd
    - lessons/119-linear-models.Rmd
    - lessons/120-gam-loess.Rmd
    - lessons/124-collaboration.Rmd
    - lessons/301-data-sources.Rmd
    - lessons/911-ethics.Rmd
    - lessons/133-reproducible-reports.Rmd
    - lessons/121-PCA.Rmd
    - lessons/122-mds.Rmd
    - lessons/123-kmean.Rmd
    - lessons/125-slides.Rmd
    - lessons/127-test-data.Rmd
    - lessons/155-dynamics-graphics.Rmd
    - lessons/140-mapping.Rmd
    - lessons/141-mapping-2.Rmd
    - lessons/142-mapping-3.Rmd
    - lessons/130-bonus-topics.Rmd
    - lessons/201-colour.Rmd
    - lessons/133-themes.Rmd
    - lessons/130-graphics-output.Rmd
    - lessons/134-reconstruction.Rmd
    - lessons/499-review.Rmd
    - lessons/901-TMI-R.Rmd
    - lessons/999-metadata.Rmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cap-location: margin
    reference-location: margin
    # citation-location: margin
    code-link: true


